// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v1/ad/click": {
            "post": {
                "description": "用户点击广告跳转前调用，换取 click_id（及 jump_url）拼进落地页；服务端按计费方式记一次有效点击。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户端接口"
                ],
                "summary": "点击埋点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App API Key",
                        "name": "X-Api-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "点击埋点请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AdClickRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.AdClickResponse"
                        }
                    }
                }
            }
        },
        "/v1/ad/impression": {
            "post": {
                "description": "素材成功渲染并被用户看到时上报，触发 CPM 扣费与展现统计。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户端接口"
                ],
                "summary": "曝光埋点",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App API Key",
                        "name": "X-Api-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "曝光埋点请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AdImpressionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ClientSimpleResponse"
                        }
                    }
                }
            }
        },
        "/v1/ad/list": {
            "post": {
                "description": "一次请求跨全部广告样式下发，按综合得分汇总取前 count 条；每条素材生成 bid_id，供后续曝光/点击/完播埋点闭环归因。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户端接口"
                ],
                "summary": "批量获取广告",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App API Key",
                        "name": "X-Api-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "批量获取广告请求（body 可空，参数亦可走 query）",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AdListRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.AdListResponse"
                        }
                    }
                }
            }
        },
        "/v1/ad/video-complete": {
            "post": {
                "description": "仅 REWARDED_VIDEO 样式：观看达到 required_duration 秒或自然播完时上报，触发 S2S 回调发奖。",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "客户端接口"
                ],
                "summary": "视频播放完毕",
                "parameters": [
                    {
                        "type": "string",
                        "description": "App API Key",
                        "name": "X-Api-Key",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "视频播放完毕请求",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AdVideoCompleteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ClientSimpleResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AdClickData": {
            "type": "object",
            "properties": {
                "click_id": {
                    "type": "string",
                    "example": "clk_7788992233"
                },
                "jump_url": {
                    "type": "string",
                    "example": "https://landing.com?clk=clk_7788992233"
                }
            }
        },
        "api.AdClickRequest": {
            "type": "object",
            "properties": {
                "ad_app_id": {
                    "type": "string",
                    "example": "app_10001"
                },
                "adjust_adid": {
                    "type": "string",
                    "example": "adj_xyz_9988"
                },
                "bid_id": {
                    "type": "string",
                    "example": "bid_20260908_0001"
                },
                "creative_id": {
                    "type": "string",
                    "example": "cr_90002"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1774213465
                },
                "user_id": {
                    "type": "string",
                    "example": "user_abc_12345"
                }
            }
        },
        "api.AdClickResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/api.AdClickData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "api.AdImpressionRequest": {
            "type": "object",
            "properties": {
                "ad_app_id": {
                    "type": "string",
                    "example": "app_10001"
                },
                "bid_id": {
                    "type": "string",
                    "example": "bid_20260908_0001"
                },
                "creative_id": {
                    "type": "string",
                    "example": "cr_90002"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1774213460
                }
            }
        },
        "api.AdListData": {
            "type": "object",
            "properties": {
                "ad_list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.AdListItem"
                    }
                },
                "loopable": {
                    "description": "Loopable 整个广告列表是否允许在客户端缓存期内循环播放。\n当且仅当列表内所有素材均可循环（视频）时为 true，任一图片素材出现则为 false。",
                    "type": "boolean",
                    "example": true
                }
            }
        },
        "api.AdListItem": {
            "type": "object",
            "properties": {
                "ad_style": {
                    "type": "string",
                    "example": "REWARDED_VIDEO"
                },
                "bid_id": {
                    "type": "string",
                    "example": "bid_20260908_0001"
                },
                "click_url": {
                    "type": "string",
                    "example": "https://landing.com?clk={CLICK_ID}"
                },
                "creative_id": {
                    "type": "string",
                    "example": "cr_90002"
                },
                "height": {
                    "type": "integer",
                    "example": 1920
                },
                "material_type": {
                    "type": "string",
                    "example": "VIDEO"
                },
                "material_url": {
                    "type": "string",
                    "example": "https://cdn.example.com/creatives/abc123.mp4"
                },
                "required_duration": {
                    "type": "integer",
                    "example": 15
                },
                "target_scene": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "APP_LAUNCH"
                    ]
                },
                "width": {
                    "type": "integer",
                    "example": 1080
                }
            }
        },
        "api.AdListRequest": {
            "type": "object",
            "properties": {
                "ad_app_id": {
                    "type": "string",
                    "example": "app_10001"
                },
                "adjust_adid": {
                    "type": "string",
                    "example": "adj_xyz_9988"
                },
                "count": {
                    "type": "integer",
                    "example": 5
                },
                "ip": {
                    "type": "string",
                    "example": "192.168.1.100"
                },
                "os": {
                    "type": "string",
                    "example": "ios"
                },
                "user_id": {
                    "type": "string",
                    "example": "user_abc_12345"
                }
            }
        },
        "api.AdListResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "data": {
                    "$ref": "#/definitions/api.AdListData"
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        },
        "api.AdVideoCompleteRequest": {
            "type": "object",
            "properties": {
                "ad_app_id": {
                    "type": "string",
                    "example": "app_10001"
                },
                "bid_id": {
                    "type": "string",
                    "example": "bid_20260908_0001"
                },
                "creative_id": {
                    "type": "string",
                    "example": "cr_90002"
                },
                "timestamp": {
                    "type": "integer",
                    "example": 1774213495
                },
                "user_id": {
                    "type": "string",
                    "example": "user_abc_12345"
                }
            }
        },
        "api.ClientSimpleResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer",
                    "example": 200
                },
                "msg": {
                    "type": "string",
                    "example": "success"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"https", "http"},
	Title:            "广告投放中心 客户端接口",
	Description:      "客户端 SDK 对接用接口：批量获取广告、曝光/点击/完播埋点。所有接口通过 HTTP Header `X-Api-Key` 鉴权（值为后台分配的 App API Key）。",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
